#!/bin/bash
# Build step: bake environment variables into env-config.js.
# Platforms run this before serving the static files.
#
# Supported env vars:
#   BANNER_MESSAGE — text shown in a banner bar at the top of the page.
#                    Leave unset (or empty) to hide the banner.
#
# To test via auto_deploy:
#   1. Open the ⚙ Env Vars modal on your deployment card.
#   2. Add BANNER_MESSAGE = "Hello from env vars!"
#   3. Redeploy.  The banner appears on the next visit.

set -e

BANNER="${BANNER_MESSAGE:-}"

# Base64-encode to avoid quote/backslash escaping inside the JS file.
BANNER_B64=$(printf '%s' "$BANNER" | base64 | tr -d '\n')

cat > env-config.js << EOF
// Auto-generated by build.sh — do not edit.
window.ENV = {
  BANNER_MESSAGE: atob("${BANNER_B64}")
};
EOF

if [ -n "$BANNER" ]; then
  echo "build.sh: BANNER_MESSAGE is set — banner will be visible."
else
  echo "build.sh: BANNER_MESSAGE is empty — banner will be hidden."
fi
