services:
  - type: static
    name: sample-site
    buildCommand: "bash build.sh"
    staticPublishPath: .
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, HEAD, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "*"
